### ISSUE TITLE
Factorial Program in cpp

### ISSUE THREAD

**Issue by shivanithorve01** [SR-Sunny-Raj/Hacktoberfest2021-DSA#1025]
Hello @SR-Sunny-Raj , I am Shivani and I am wanted to contribute in your repo with program to find factorial of a number. Could you assign this issue to me ?

**Comment by vivek-0110** [comment]
Hello @SR-Sunny-Raj , Vivek here! I request you to kindly assign this issue to me as I want to contribute to your repository with an optimized solution on this issue. Thank you.

**Comment by piyush362** [comment]
Hey I want to contribute in this issue. Kindly assign me this issue.
Thank You.
