### ISSUE TITLE
Rotate an array clockwise 

### ISSUE THREAD

**Issue by shefali12-ab** [SR-Sunny-Raj/Hacktoberfest2021-DSA#1065]
Hii, I would like to contribute, by providing a solution to this problem in C++ that is to rotate an array clockwise, with a commented explanation. Looking forward to your reply.
Thank you.

**Comment by Meghwantsingh** [comment]
Hi , I'm new to this but i would like to try this problem can i.

**Comment by shefali12-ab** [comment]
@Meghwantsingh I am working on this issue, you can create a new issue and contribute.

**Comment by prehans** [comment]
Can you assign this issue to me? @SR-Sunny-Raj
