### ISSUE TITLE
Sort Colors

### ISSUE THREAD

**Issue by harshita9621** [SR-Sunny-Raj/Hacktoberfest2021-DSA#1115]
Given an array nums with n objects colored red, white, or blue, sort them in-place so that objects of the same color are adjacent, with the colors in the order red, white, and blue.
Input: nums = [2,0,2,1,1,0]
Output: [0,0,1,1,2,2]

Look forward to response.
Thank you.

**Comment by krishnagupta1543** [comment]
public class Issue {
    static void swap(int [] a, int j, int k){
        int temp = a[j];
        a[j] = a[k];
        a[k] = temp;
    }
    public static void main(String[] args) {
        int [] arr = {0, 1, 2, 1, 0, 2};
        int i = 0;
        while(i < arr.length)
        {
            for (int j = 0; j < arr.length-1; j++) {
                if(arr[j]>arr[j+1])
                {
                    swap(arr,j,j+1);
                }
            }
            i++;

        }
        System.out.println(Arrays.toString(arr));
    }
}
