### ISSUE TITLE
More Pattern Questions in Java

### ISSUE THREAD

**Issue by sagarcode28** [SR-Sunny-Raj/Hacktoberfest2021-DSA#1159]
Hey! @SR-Sunny-Raj 
I Want to Add More Pattern Questions to Pattern folder.
Can You Please Assign it to Me?

**Comment by koustav2001** [comment]
HI! @SR-Sunny-Raj  I would like to add more pattern questions.Please assign the issue to me.Thank You

**Comment by ArihantJain123** [comment]
I want to add new Questions Can you assign this issue to me ? Thank you
