### ISSUE TITLE
Wanted to add Dijkstra shortest path algorithm in c++ 

### ISSUE THREAD

**Issue by Abhishek-5854** [SR-Sunny-Raj/Hacktoberfest2021-DSA#1522]

**Comment by amankumar-2001** [comment]
Hello sir, I would like to contribute in this repo and wanna fix using C++.
For my programming skills you can visit my codechef profile  [apcode15](https://www.codechef.com/users/apcode15)
Please assign this to me under Hacktoberfest 2022.
Thank you!!

**Comment by seemaPatl** [comment]
Hi Sunny, 
I would like to contribute a few questions related to the topic mentioned.
Profile : seemaPatl .

**Comment by SR-Sunny-Raj** [comment]
Please make your contribution in this repository https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all for 2022 hacktoberfest.
