### ISSUE TITLE
Wants to add Remove Duplicate from a Sorted Array in Java?

### ISSUE THREAD

**Issue by AyushCSE04** [SR-Sunny-Raj/Hacktoberfest2021-DSA#1543]
No description

**Comment by AyushCSE04** [comment]
Can You assign this to me ?

**Comment by Arpit350** [comment]
Hii @SR-Sunny-Raj Can you assigned to me? I have most optimised Approch.

**Comment by Ayushitgithub** [comment]
can u please assign this issue to me?

**Comment by shivam0084** [comment]
can u please assign this issue to me?

**Comment by satyam-mahajan** [comment]
Hii @SR-Sunny-Raj please assign it to me , I am interested ?

**Comment by shivam0084** [comment]
hii @SR-Sunny-Raj  can u please assign this issue to me?

**Comment by rohanyrane** [comment]
Please assign me this issue

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by SR-Sunny-Raj** [comment]
Guys this repository is not for hacktoberfest 2022 but if you still want to work on the issue I'm assigning @AyushCSE04  for this.

**Comment by Ashishbit01** [comment]
can you this to me
