### ISSUE TITLE
Trees Leetcode Solutions

### ISSUE THREAD

**Issue by VaibhavPaliwal0007** [SR-Sunny-Raj/Hacktoberfest2021-DSA#170]
I want to add solutions of Maximum Width of a binary tree and vertical order traversal of a binary tree 

https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree
https://leetcode.com/problems/maximum-width-of-binary-tree/

<img width="249" alt="image" src="https://user-images.githubusercontent.com/78612380/135615389-dfd5de93-be61-4aa9-8ab7-c3bbda4e216f.png">

Do assign it to me...

**Comment by SR-Sunny-Raj** [comment]
@VaibhavPaliwal0007 assigned

**Comment by ct-27** [comment]
I want to add solutions of Zigzag level order traversal and right side view of a binary tree.
https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/
https://leetcode.com/problems/binary-tree-right-side-view/
