### ISSUE TITLE
Search in nearly sorted array

### ISSUE THREAD

**Issue by irit2607** [SR-Sunny-Raj/Hacktoberfest2021-DSA#180]
I want to contribute to the problem.

**Comment by drishyadamodaran** [comment]
I would like to contribute.

**Comment by SR-Sunny-Raj** [comment]
ok @drishyadamodaran You can contribute to this problem. @irit2607 you can make your contribution for some different problem.

**Comment by drishyadamodaran** [comment]
> ok @drishyadamodaran You can contribute to this problem. @irit2607 you can make your contribution for some different problem.

please do check it
