### ISSUE TITLE
Nearest smaller to the left

### ISSUE THREAD

**Issue by irit2607** [SR-Sunny-Raj/Hacktoberfest2021-DSA#182]
I want to contribute to this problem using a stack technique.

**Comment by sneha-baser** [comment]
@irit2607 I would like to solve issue. could you please assign it to me?

**Comment by snehashukkla** [comment]
I can solve this issue if you could assign it to me.

**Comment by DhabekarHarsh** [comment]
I want to solve this issue if you could assign it to me.

**Comment by tanvideshmukh29** [comment]
Hi! I would love to work on this issue ,
I will try to solve this using stack..
please assign it to me.
