### ISSUE TITLE
RightView of Binary Tree

### ISSUE THREAD

**Issue by sneha-baser** [SR-Sunny-Raj/Hacktoberfest2021-DSA#201]

**Comment by ct-27** [comment]
I would like to do this problem. Please assign it to me.

**Comment by SR-Sunny-Raj** [comment]
@sneha-baser Please don't create an isuue. Kindly make a pull request if you know any program that you think should be in this repo. Your pull request will be merged shortly.

**Comment by SR-Sunny-Raj** [comment]
> I would like to do this problem. Please assign it to me.

Please work on some different problem.
