### ISSUE TITLE
Return a string after toggling case of each character

### ISSUE THREAD

**Issue by chandu6111** [SR-Sunny-Raj/Hacktoberfest2021-DSA#233]
This comes under String questions. It is a question from pepcoding. I wanted to code it in java.
Basically, we toggle the case of every letter of a string 
Example:
input: 
pepCODinG
output: 
PEPcodINg

**Comment by chandu6111** [comment]
Could you tell me if I should proceed with it, @SR-Sunny-Raj

**Comment by DhabekarHarsh** [comment]
I want solve this issue .Assign it to me.

**Comment by SR-Sunny-Raj** [comment]
@chandu6111 Great Work👍🏻
