### ISSUE TITLE
Maximum Path Sum

### ISSUE THREAD

**Issue by ama29n** [SR-Sunny-Raj/Hacktoberfest2021-DSA#258]
I want to add a solution for the Maximum Path Sum Question of Leetcode, under the folder Tree

Here is the link to the question - https://leetcode.com/problems/binary-tree-maximum-path-sum/submissions/

<img src="https://user-images.githubusercontent.com/85681334/135667126-5667cad1-86c9-4df6-bb1c-27b8330fe814.png" width="700">

<img src="https://user-images.githubusercontent.com/85681334/135667129-844108e6-3fd0-4dfb-8324-2f3f258f657f.png" width="700">

**Comment by kaushiki29** [comment]
Hi I want to work on this issue, please assign it to me.

**Comment by SR-Sunny-Raj** [comment]
> I want to add a solution for the Maximum Path Sum Question of Leetcode, under the folder Tree
> 
> Here is the link to the question - https://leetcode.com/problems/binary-tree-maximum-path-sum/submissions/
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85681334/135667126-5667cad1-86c9-4df6-bb1c-27b8330fe814.png">
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85681334/135667129-844108e6-3fd0-4dfb-8324-2f3f258f657f.png">

Great Work 👍🏻

**Comment by SR-Sunny-Raj** [comment]
> I want to add a solution for the Maximum Path Sum Question of Leetcode, under the folder Tree
> 
> Here is the link to the question - https://leetcode.com/problems/binary-tree-maximum-path-sum/submissions/
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85681334/135667126-5667cad1-86c9-4df6-bb1c-27b8330fe814.png">
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85681334/135667129-844108e6-3fd0-4dfb-8324-2f3f258f657f.png">

Go for it👍🏻
