### ISSUE TITLE
codechef-airline restricitions problem

### ISSUE THREAD

**Issue by Harshit3107** [SR-Sunny-Raj/Hacktoberfest2021-DSA#268]
I want to add codechef airline restrictions problem 
link:
https://www.codechef.com/SEPT21C/problems/AIRLINE

**Comment by vabhv1903** [comment]
assign this to me

**Comment by shubhankit123** [comment]
Please assign it to me

**Comment by pandapritish25** [comment]
I can do this problem kindly assign to me
