### ISSUE TITLE
Minimum Window Substring

### ISSUE THREAD

**Issue by divya-rai-42** [SR-Sunny-Raj/Hacktoberfest2021-DSA#279]
Given two strings s and t , return the minimum window substring of s such that every character in t (including duplicates) is included in the window.

Example: s="adobecodebanc"
               t="abc"
    Output: "banc"
The minimum length of the the substring of s that includes all the characters of  t is "banc"

**Comment by divya-rai-42** [comment]
@SR-Sunny-Raj  Please assign this issue to me!

**Comment by shubhankit123** [comment]
@SR-Sunny-Raj  Please assign it to me

**Comment by tanvideshmukh29** [comment]
Hi! I would love to work on this issue..

Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string "".

The testcases will be generated such that the answer is unique.

A substring is a contiguous sequence of characters within the string.

https://leetcode.com/problems/minimum-window-substring/



please assign it to me.

**Comment by SR-Sunny-Raj** [comment]
@divya-rai-42 and @tanvideshmukh29 you can contribute the solution to your problem and @shubhankit123 please try some other problem if you can.

**Comment by tanvideshmukh29** [comment]
ok thanks!

**Comment by aishapervin** [comment]
@SR-Sunny-Raj can we create more than 1 PR's here?will more than 1 be merged here?

**Comment by harshita9621** [comment]
@SR-Sunny-Raj can you please assign me this mam. I am part of hacktoberfest2021.

**Comment by SR-Sunny-Raj** [comment]
> @SR-Sunny-Raj can we create more than 1 PR's here?will more than 1 be merged here?

Yes you can do that.

**Comment by SR-Sunny-Raj** [comment]
> @SR-Sunny-Raj can you please assign me this man. I am part of hacktoberfest2021.

You can try some other problem.
