### ISSUE TITLE
Count total set bits with time complexity O(logN)

### ISSUE THREAD

**Issue by NevinSelby** [SR-Sunny-Raj/Hacktoberfest2021-DSA#288]
I would like to add the following question
Link: https://practice.geeksforgeeks.org/problems/count-total-set-bits-1587115620/1

**Comment by NevinSelby** [comment]
assign this to me

**Comment by SR-Sunny-Raj** [comment]
> assign this to me

Ok you can make your contribution on this.

**Comment by NevinSelby** [comment]
Can you pls add the hacktoberfest tag on this?
