### ISSUE TITLE
Finding middle element of a linked list

### ISSUE THREAD

**Issue by NevinSelby** [SR-Sunny-Raj/Hacktoberfest2021-DSA#346]
I would like to add this as a part of hacktoberfest2021.
Link: https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1

**Comment by NevinSelby** [comment]
pls add the tag hacktoberfest and assign this to me

**Comment by vacodr** [comment]
Hi I would like to solve this problem please assign this task to me thanks

**Comment by tanvideshmukh29** [comment]
I would love to work on this issue....

Given the head of a singly linked list, return the middle node of the linked list.

If there are two middle nodes, return the second middle node.

https://leetcode.com/problems/middle-of-the-linked-list/

please assign this to me.

**Comment by SR-Sunny-Raj** [comment]
@vacodr you can try some different problem.

**Comment by SR-Sunny-Raj** [comment]
> I would love to work on this issue....
> 
> Given the head of a singly linked list, return the middle node of the linked list.
> 
> If there are two middle nodes, return the second middle node.
> 
> https://leetcode.com/problems/middle-of-the-linked-list/
> 
> please assign this to me.

Go for it👍🏻
