### ISSUE TITLE
For Uploading a new question in graphs folder. 

### ISSUE THREAD

**Issue by VibhuGautam** [SR-Sunny-Raj/Hacktoberfest2021-DSA#363]
How Can I upload a new question alongside C++ code. Should I have to write the question separately in a readme file or I can comment it out in the code itself ?

**Comment by SR-Sunny-Raj** [comment]
> How Can I upload a new question alongside C++ code. Should I have to write the question separately in a readme file or I can comment it out in the code itself ?

Comment Out in the code.

**Comment by VibhuGautam** [comment]
Ok thanks a lot !

**Comment by tanvideshmukh29** [comment]
Can I add solution of leetcode. questions of graphs?

https://leetcode.com/problems/redundant-connection/

https://leetcode.com/problems/course-schedule-ii/

**Comment by SR-Sunny-Raj** [comment]
> Can I add solution of leetcode. questions of graphs?
> 
> https://leetcode.com/problems/redundant-connection/
> 
> https://leetcode.com/problems/course-schedule-ii/

Yes go for it👍🏻
