### ISSUE TITLE
Ceil of a number in sorted array

### ISSUE THREAD

**Issue by SanskritiKushik5** [SR-Sunny-Raj/Hacktoberfest2021-DSA#40]
This is a program of Binary Search. Can I contribute a solution to this problem?

**Comment by SR-Sunny-Raj** [comment]
Yes @SanskritiKushik5 You can contribute it into it's respective folder. Like in your case you can contribute Binary Search in the folder made for Searching Algorithm.

**Comment by preeti-14-7** [comment]
Can i work on this under hacketoberfest 2021

**Comment by SR-Sunny-Raj** [comment]
@preeti-14-7 yes you can make your contribution in this repo.

**Comment by preeti-14-7** [comment]
> @preeti-14-7 yes you can make your contribution in this repo.

we both can work on same issue ?

**Comment by SR-Sunny-Raj** [comment]
> > @preeti-14-7 yes you can make your contribution in this repo.
> 
> we both can work on same issue ?

If you know any other searching algorithm like for eg. interpolation search, You can do that.

**Comment by pandapritish25** [comment]
hello sir can i make contribution in this repo
I can give all the cases of upper bounds lower bounds and all the algorithms

**Comment by SR-Sunny-Raj** [comment]
> hello sir can i make contribution in this repo I can give all the cases of upper bounds lower bounds and all the algorithms

Yes you can contribute but make sure to add the program in the respective folder.
