### ISSUE TITLE
Unable to push the code.

### ISSUE THREAD

**Issue by VibhuGautam** [SR-Sunny-Raj/Hacktoberfest2021-DSA#440]
remote: Permission to SR-Sunny-Raj/Hacktoberfest2021-DSA.git denied
fatal: unable to access 'https://github.com/SR-Sunny-Raj/Hacktoberfest2021-DSA.git/': The requested URL returned error: 403

Should I push the added code in master ? As I've made a separate branch "cses" for the added code.  
Please look into this matter

**Comment by krishnan-tech** [comment]
1. Fork this repository.
2. Now you will see code in your repo, then clone your repo.
3. Make Changes in your repo
4. push the code in the forked (yours) repo
5. Then, at last, open pull request 

And Boom, you are good to go 😄

**Comment by VibhuGautam** [comment]
Yes I'm doing this only. 
I've forked and cloned into my local. Then I created a separate branch and added a cpp file then I pushed but that error was showing.

**Comment by VibhuGautam** [comment]
Ya thanks man. I was cloning before then I was forking. Thanks !!
