### ISSUE TITLE
Hacktoberfest is writing Excluded Project

### ISSUE THREAD

**Issue by VibhuGautam** [SR-Sunny-Raj/Hacktoberfest2021-DSA#484]

**Comment by PRA-developer-TIK** [comment]
kat gaya !!

**Comment by euhidaman** [comment]
It's doing this because, people are putting codes and scripts, which are easily available in the internet by copy and pasting.
Such are Leetcode , GFG, Codeforces or some other competitive site answers.

**Comment by SR-Sunny-Raj** [comment]
> It's doing this because, people are putting codes and scripts, which are easily available in the internet by copy and pasting. Such as Leetcode , GFG, Codeforces or some other competitive site answers.

Exactly!! As previously when I had checked it it was being considered as a valid project. But now don't know what just happened and now it's showing as an excluded project.
