### ISSUE TITLE
K-Closest point to origin

### ISSUE THREAD

**Issue by Priya272** [SR-Sunny-Raj/Hacktoberfest2021-DSA#491]
In this question we will be given points and we need to find the closest point from origin.
Input:-
points = [[3,3],[5,-1],[-2,4]],  k = 2

Output:-
[[3,3],[-2,4]]

**Comment by Priya272** [comment]
@SR-Sunny-Raj please assign this issue to me.!!
I will solve this question using heap 
and language I will be using  would be C++.

**Comment by OmPr366** [comment]
Hey there !
I have done this type of question, please assign this to me .
I will happy to contribute my code .

Thank You:)
