### ISSUE TITLE
Nearest smaller no to left

### ISSUE THREAD

**Issue by Priya272** [SR-Sunny-Raj/Hacktoberfest2021-DSA#518]
like if we have a array like
arr={2,7,4,8}
we need to find the nearest smaller no for each element in a array.
output:
{-1,2,2,4}

**Comment by Priya272** [comment]
@SR-Sunny-Raj please assign this issue to me!!
i want to do this question using C++ as language and i will use stack data structure for this question

**Comment by vivekarora-02** [comment]
Hey, there!

I would like to contribute to this issue can you please assign me?

ThankYou!!

**Comment by bhavitjain** [comment]
Hey, there!

i have already solved this question please it it me. so that i can submit it my code takes O(n) time and space.

Thank you!!

**Comment by OmPr366** [comment]
Hey ! 

I have done many   questions related this , please assign me .
I would like to contribute my code.

Thank You :)
