### ISSUE TITLE
Adding Rat-Maze problem with efficient solution.

### ISSUE THREAD

**Issue by Gupta-Nikhil85** [SR-Sunny-Raj/Hacktoberfest2021-DSA#576]
Story: You have to find a path through which the rat move from the starting position (0,0) to the final position where cheese is (n,n). List the total no of possible paths which the rat can take to reach the cheese.

Input
A file whose first line contains the size of the square maze The next n lines contain n binary values separated by space. 0 denotes an open cell while 1 denotes a blocked cell. You have to find paths which contain only cells which are open, and finally print the total no of such unique paths. Retracing the 1 or more cells back and forth is not considered a new path. The set of all cells covered in a single path should be unique from other paths

Output
The output should be the total no of paths possible on the first line

Question link:- https://www.codechef.com/problems/BPHC03

**Comment by manisha-4** [comment]
I have  created a PR (PR #587 ). please review and merge.

**Comment by shubhamhere** [comment]
Hey!! I want to work on this issue I will upload the solution in C++, please assign this to me :)
