### ISSUE TITLE
Binary search 

### ISSUE THREAD

**Issue by tandrimasingha** [SR-Sunny-Raj/Hacktoberfest2021-DSA#608]
Please @SR-Sunny-Raj Sir Assign this task to me

**Comment by The-Divyansh** [comment]
Please assign it to me @SR-Sunny-Raj

**Comment by shubhamhere** [comment]
Please assign it to me @SR-Sunny-Raj  .happy to contribute : )

**Comment by OmPr366** [comment]
Hey there ! 
I have done many questions on Binary search , please assign this to me .
I will happy to contribute my code .

Thank You:)
