### ISSUE TITLE
Complex number multiplication problem (leetcode) .

### ISSUE THREAD

**Issue by Omgupta0312** [SR-Sunny-Raj/Hacktoberfest2021-DSA#695]
A complex number can be represented as a string on the form "real+imaginaryi" where:

real is the real part and is an integer in the range [-100, 100].
imaginary is the imaginary part and is an integer in the range [-100, 100].
i2 == -1.
Given two complex numbers num1 and num2 as strings, return a string of the complex number that represents their multiplications.

**Comment by Omgupta0312** [comment]
Sir, Please assign me this task.

**Comment by Omgupta0312** [comment]
Sir did you close that.

**Comment by SR-Sunny-Raj** [comment]
> Sir, Please assign me this task.

You can work on this. I had assigned you that's why I closed it.

**Comment by Omgupta0312** [comment]
Ohh okay thankyou sir . Sorry for bothering you
