### ISSUE TITLE
Friends Pairing problem

### ISSUE THREAD

**Issue by sandeep-07** [SR-Sunny-Raj/Hacktoberfest2021-DSA#864]
**Is your feature request related to a problem? Please describe.**
Problem Link:- https://practice.geeksforgeeks.org/problems/friends-pairing-problem5425/1#

**Describe the solution you'd like**
I have used top-down dynamic programming approach to solve the question

**Describe alternatives you've considered**
It can also be solved using bottom up approach , recursion 

**Additional context**
NA

**Comment by ankur7864** [comment]
please assign this to me

**Comment by Mgs25** [comment]
I can provide a efficient solution, so, let me solve this one!
