### ISSUE TITLE
Missing "Decode String" problem in Stacks.

### ISSUE THREAD

**Issue by archana-9430** [SR-Sunny-Raj/Hacktoberfest2021-DSA#894]
**Is your feature request related to a problem? Please describe.**
This problem is to decode a given encoded string. Eg, for s = "3[a]2[bc]", output- "aaabcbc".
Problem Link: https://leetcode.com/problems/decode-string/

**Describe the solution you'd like**
I would use Stack Data Structure to implement this.

**Describe alternatives you've considered**
It can also be implemented using DFS.

**Additional context**
NA

**Comment by SR-Sunny-Raj** [comment]
> > I would like to work on this issue. Assign it to me
> 
> @SR-Sunny-Raj Check PR #934. Do let me know if any improvement is needed.

Great Work @archana-9430 . Keep it up👍🏻

**Comment by archana-9430** [comment]
@SR-Sunny-Raj Is your repository excluded from Hactoberfest'21?

**Comment by SR-Sunny-Raj** [comment]
> @SR-Sunny-Raj Is your repository excluded from Hactoberfest'21?

Yes, it's marked as excluded because of spamming pull requests. Don't know why but hacktoberfest team is doing this with every other projects out there on github. Hope it would be included again, but for now to be on the safe side you can make your pull request in any of your own repo so that it would be counted for hacktoberfest.

**Comment by archana-9430** [comment]
> > @SR-Sunny-Raj Is your repository excluded from Hactoberfest'21?
> 
> Yes, it's marked as excluded because of spamming pull requests. Don't know why but hacktoberfest team is doing this with every other projects out there on github. Hope it would be included again, but for now to be on the safe side you can make your pull request in any of your own repo so that it would be counted for hacktoberfest.

Okay, thanks :-)
