### ISSUE TITLE
Sum and product of n terms of GP series on Python

### ISSUE THREAD

**Issue by TheDesTrucToRR** [SR-Sunny-Raj/Hacktoberfest2021-DSA#911]
A python program to find sum and product of n terns of GP series.

**Comment by TheDesTrucToRR** [comment]
@SR-Sunny-Raj please assign this issue to me. I would like to work on it.

**Comment by SiddheshKanawade** [comment]
Please assign this problem to me I would like to work on it, trust me I am good at it.

**Comment by TheDesTrucToRR** [comment]
@SiddheshKanawade Sorry but I m currently working on it. So please look for some other issue.

**Comment by TheDesTrucToRR** [comment]
@SR-Sunny-Raj why did u closed this issue.

**Comment by SR-Sunny-Raj** [comment]
> @SR-Sunny-Raj why did u closed this issue.

You do the program. I just closed the issue otherwise others will ask to assign them for it.
