### ISSUE TITLE
450. Delete Node in a BST

### ISSUE THREAD

**Issue by dpshikha476** [SR-Sunny-Raj/Hacktoberfest2021-DSA#915]
I want to add solution of this problem present on Leetcode in C++.
Problem Link - https://leetcode.com/problems/delete-node-in-a-bst/
Please assign me this.

**Comment by HarshJ27** [comment]
Hi, @SR-Sunny-Raj I am Harsh Jha. I am an aspiring web developer and a computer science engineering student. I have a knowledge of DSA as it is in my curriculum. I can solve this problem. Please allow me to handle this. Thank You.

**Comment by HarshJ27** [comment]
> > Hi, @SR-Sunny-Raj I am Harsh Jha. I am an aspiring web developer and a computer science engineering student. I have a knowledge of DSA as it is in my curriculum. I can solve this problem. Please allow me to handle this. Thank You.
> 
> @HarshJ27 This problem has already been assigned. You can try working on some other problem.

Okay thank you for the info @SR-Sunny-Raj
