### ISSUE TITLE
Diagonal Traversal of a tree

### ISSUE THREAD

**Issue by saujanya02** [SR-Sunny-Raj/Hacktoberfest2021-DSA#940]
Printing all diagonal elements in a binary tree belonging to the same line.

**Comment by Anova07** [comment]
@SR-Sunny-Raj  Please assign this issue to me as the person has not responded yet.

**Comment by Anova07** [comment]
I have created  a new PR - "Create diagonalTraversal_of_BinaryTree.cpp #1177"
@SR-Sunny-Raj  please accept it.
I have mentioned it there too, you can close both of them after merging, 
Do let me know if i need to do anything more.

Thank you.
