### ISSUE TITLE
138. Copy List with Random Pointer

### ISSUE THREAD

**Issue by dikshamalik2552** [SR-Sunny-Raj/Hacktoberfest2021-DSA#996]
I want to add the solution to this problem present on Leetcode in Java.
Problem Link - https://leetcode.com/problems/copy-list-with-random-pointer/
Please assign me this.

**Comment by vivekarora-02** [comment]
Hey there,
Can you please assign me this issue?

ThankYou!

**Comment by Mehul-Thuletiya** [comment]
Assign the issue to me. I will fix it

**Comment by xhukla** [comment]
Hey there, can you please assign me this issue? I want to do it in C++. I have just completed DSA with C++ course on Coding Ninjas.
